import { body } from 'express-validator';

export const validateOnboardingStep = [
  body('displayName').optional().trim().isString(),
  body('track').optional({ checkFalsy: true }).isString(),
  body('primaryLanguage').optional({ checkFalsy: true }).isArray({ max: 2 }),
  body('primaryLanguage.*').optional({ checkFalsy: true }).isString(),
  body('otherLanguage').optional({ checkFalsy: true }).isString(),
  body('frontendFramework').optional({ checkFalsy: true }).isArray(),
  body('frontendFramework.*').optional({ checkFalsy: true }).isString(),
  body('otherFrontendFramework').optional({ checkFalsy: true }).isString(),
  body('backendFramework').optional({ checkFalsy: true }).isArray(),
  body('backendFramework.*').optional({ checkFalsy: true }).isString(),
  body('otherBackendFramework').optional({ checkFalsy: true }).isString(),
  body('database').optional({ checkFalsy: true }).isArray({ max: 2 }),
  body('database.*').optional({ checkFalsy: true }).isString(),
  body('otherDatabase').optional({ checkFalsy: true }).isString(),
  body('experienceLevel').optional({ checkFalsy: true }).isString(),
  body('experienceYears').optional({ checkFalsy: true }).isInt({ min: 0, max: 20 }),
  body('targetRole').optional({ checkFalsy: true }).isString(),
  body('targetCompanies').optional({ checkFalsy: true }).isArray(),
  body('targetCompanies.*').optional({ checkFalsy: true }).isString(),
  body('additionalSkills').optional({ checkFalsy: true }).isArray(),
  body('additionalSkills.*').optional({ checkFalsy: true }).isString(),
  body('interviewTimeline').optional({ checkFalsy: true }).isString(),
  body('weeklyGoal').optional({ checkFalsy: true }).isString(),
  body('currentStep').optional({ checkFalsy: true }).isInt({ min: 1, max: 8 }),
];
