import mongoose, { Schema, Document } from 'mongoose';

// ─── COMPANY INTELLIGENCE ──────────────────────────
// Stored separately, seeded by admin or generated by Claude
// Powers the company specific focus in every ritual

export interface ICompanyProfile extends Document {
  name: string;
  slug: string;
  tier: 'faang' | 'product' | 'service' | 'startup' | 'finance';
  interviewRounds: Array<{
    roundName: string;
    focus: string[];
    weight: number; // 0-100, how heavily weighted this round is
    tips: string[];
  }>;
  knownTopics: string[];      // what they actually ask
  behavioralFocus: string[];  // leadership principles etc
  difficultyLevel: 'low' | 'medium' | 'high' | 'very_high';
  averageRounds: number;
  interviewDurationMinutes: number;
  whatTheyReallyWantToHear: string[];
  commonMistakes: string[];
  insiderTips: string[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const CompanyProfileSchema = new Schema({
  name: { type: String, required: true },
  slug: { type: String, required: true, unique: true },
  tier: { 
    type: String, 
    enum: ['faang', 'product', 'service', 'startup', 'finance'],
    required: true 
  },
  interviewRounds: [{
    roundName: { type: String },
    focus: [{ type: String }],
    weight: { type: Number, min: 0, max: 100 },
    tips: [{ type: String }]
  }],
  knownTopics: [{ type: String }],
  behavioralFocus: [{ type: String }],
  difficultyLevel: { 
    type: String, 
    enum: ['low', 'medium', 'high', 'very_high'] 
  },
  averageRounds: { type: Number },
  interviewDurationMinutes: { type: Number },
  whatTheyReallyWantToHear: [{ type: String }],
  commonMistakes: [{ type: String }],
  insiderTips: [{ type: String }],
  isActive: { type: Boolean, default: true }
}, { timestamps: true });

export const CompanyProfile = mongoose.model<ICompanyProfile>(
  'CompanyProfile', 
  CompanyProfileSchema
);
